festive_days = {

  # india festivals 
    "14-01": "Makar Sakranti is a harvest festival celebrated across India with different names and traditions.",
    "15-01": "Pongal is a four-day harvest festival celebrated in Tamil Nadu to mark the end of winter and the onset of spring.",
    "26-01": "Basant Panchami is a Hindu festival celebrating Saraswati, the goddess of knowledge, music, arts, and science.",
    "18-02": "Maha Shivratri is a Hindu festival celebrated in honor of Lord Shiva, marking the day of his marriage to Goddess Parvati.",
    "8-03": "Holi, known as the Festival of Colors, marks the arrival of spring and the victory of good over evil.",
    "22-03": "Mewar festival is celebrated in Udaipur to welcome the arrival of spring and honor Goddess Parvati.",
    "14-04": "Baisakhi is a Sikh festival marking the formation of the Khalsa community and the Sikh New Year.",
    "13-04": "Bihu is a festival celebrated in Assam, marking the Assamese New Year and the arrival of the spring season.",
    "5-05": "Buddha Jayanti celebrates the birth, enlightenment, and death of Gautama Buddha, emphasizing peace and non-violence.",
    "22-04": "Eid Ul Fitr marks the end of Ramadan, the Islamic holy month of fasting, with prayers, feasts, and charity.",
    "20-06": "Ratha Yatra is a Hindu chariot festival celebrated in Puri, Odisha, dedicated to Lord Jagannath, Lord Balabhadra, and Devi Subhadra.",
    "29-06": "Hemis festival is a cultural extravaganza in Ladakh, celebrating the birth anniversary of Guru Padmasambhava.",
    "30-08": "Raksha Bandhan celebrates the bond of love and protection between brothers and sisters with the tying of a sacred thread.",
    "6-08": "Janmashtami celebrates the birth of Lord Krishna, with fasting, devotional singing, and enactment of Krishna's childhood stories.",
    "15-08": "Independence Day in India celebrates the nation's independence from British rule on August 15, 1947.",
    "20-08": "Onam is a harvest festival celebrated in Kerala, featuring boat races, floral decorations, and traditional dance.",
    "19-09": "Ganesh Chaturthi celebrates the birth of Lord Ganesha, the elephant-headed god of wisdom and prosperity.",
    "15-10": "Navratri is a nine-night Hindu festival celebrated with dance and worship, honoring Goddess Durga in her various forms.",
    "24-10": "Dussehra, also known as Vijayadashami, marks the victory of Lord Rama over the demon king Ravana.",
    "12-11": "Diwali, the Festival of Lights, celebrates the victory of light over darkness and good over evil.",
    "27-11": "Gurupurab commemorates the birth anniversary of Guru Nanak, the founder of Sikhism.",
    "25-12": "Christmas is celebrated to commemorate the birth of Jesus Christ.",

    # other festivals 

    "1-01": "New Year's Day is celebrated globally to mark the beginning of the new year.",
    "31-10": "Halloween is celebrated in many countries on October 31st, involving activities like trick-or-treating and costume parties.",
    "14-02": "Valentine's Day is celebrated on February 14th as a day of love and romance.",
    "4-07": "Independence Day in the United States commemorates the adoption of the Declaration of Independence.",
    "17-03": "St. Patrick's Day is a cultural and religious celebration held on March 17th, the traditional death date of Saint Patrick.",
    "7-07": "Tanabata, also known as the Star Festival, is a Japanese festival celebrating the meeting of the deities Orihime and Hikoboshi.",
    "1-10": "Chinese National Day celebrates the founding of the People's Republic of China on October 1st.",
    "19-04": "Patriots' Day in Massachusetts commemorates the battles of Lexington and Concord, which were the first battles of the American Revolutionary War.",
    "31-12": "New Year's Eve is celebrated on December 31st, the final day of the Gregorian calendar year, with parties and festivities.",
    "20-07": "Colombian Independence Day celebrates the day Colombia gained independence from Spain.",
    "23-04": "St. George's Day is the feast day of Saint George and the national day of England, marked by parades and celebrations.",
    "25-04": "Anzac Day is a national day of remembrance in Australia and New Zealand that commemorates all Australians and New Zealanders who served and died in wars and conflicts.",
    "6-12": "Dia de la Constitución (Constitution Day) in Spain celebrates the Spanish Constitution of 1978.",
    "26-12": "Boxing Day is a holiday celebrated the day after Christmas Day, occurring on December 26th.",
    "18-04": "Independence Day in Zimbabwe celebrates the independence of Zimbabwe from the United Kingdom on April 18, 1980.",
    "8-12": "Immaculate Conception Day celebrates the belief in the Immaculate Conception of the Virgin Mary.",
    "28-06": "Family Day in Ukraine celebrates the importance of family values and traditions.",
    "6-01": "Epiphany, also known as Three Kings' Day, celebrates the revelation of God incarnate as Jesus Christ.",
    "2-11": "All Souls' Day is a day of prayer for the souls of all the faithful departed.",
    "24-05": "Eid al-Fitr marks the end of Ramadan, the Islamic holy month of fasting.",
    "18-06": "Juneteenth is a holiday commemorating the emancipation of enslaved African Americans in the United States.",
    "12-07": "Malala Day celebrates the birthday of Malala Yousafzai, a Pakistani activist for female education and the youngest Nobel Prize laureate.",
    "5-07": "Independence Day in Algeria commemorates Algeria's independence from France on July 5, 1962.",
    "11-02": "National Foundation Day in Japan celebrates the foundation of Japan and the accession of its first emperor, Emperor Jimmu, in 660 BC.",
    "21-09": "International Day of Peace, also known as World Peace Day, is observed around the world each year on September 21st.",
    "26-06": "Independence Day in Madagascar celebrates Madagascar's independence from France on June 26, 1960.",
    "22-09": "Independence Day in Mali celebrates Mali's independence from France on September 22, 1960.",
    "6-04": "Chakri Memorial Day in Thailand commemorates the establishment of the Chakri Dynasty and the founding of Bangkok by King Rama I.",
    "10-12": "Constitution Day in Thailand commemorates the promulgation of the first permanent constitution of Thailand in 1932.",
    "28-05": "Menstrual Hygiene Day aims to raise awareness about the importance of good menstrual hygiene management worldwide.",
    "15-05": "International Day of Families honors the role of families in society and promotes awareness of issues relating to families.",
    "10-11": "National Day in Morocco celebrates Morocco's independence from France and Spain on November 18, 1956.",
    "1-11": "All Saints' Day is a Christian festival celebrated in honor of all the saints, known and unknown.",
    "14-08": "Independence Day in Pakistan marks the day Pakistan gained independence from the British Empire on August 14, 1947.",
    "17-08": "Indonesian Independence Day commemorates the Indonesian Declaration of Independence on August 17, 1945.",
    "1-05": "International Workers' Day, also known as Labour Day or May Day, celebrates the achievements of workers and labor movements.",
    "1-12": "World AIDS Day aims to raise awareness of the AIDS pandemic caused by the spread of HIV infection and to mourn those who have died of the disease.",
    "25-01": "Burns Night celebrates the life and poetry of the Scottish poet Robert Burns.",
    "24-06": "Midsummer, also known as the summer solstice, is a celebration of the longest day of the year in the Northern Hemisphere.",
    "26-10": "Deepavali, the Festival of Lights, is celebrated by Hindus, Sikhs, Jains, and Buddhists to signify the victory of light over darkness and good over evil.",
    "7-04": "Day of the Dead is a Mexican holiday that honors deceased loved ones with offerings of food, drink, and celebrations.",
    "2-04": "International Children's Book Day promotes the importance of children's literature and encourages reading among young people worldwide.",
    "21-06": "World Music Day celebrates the cultural and artistic significance of music around the world.",
    "6-07": "World Chocolate Day celebrates the delicious treat and its history around the world.",
    "3-10": "German Unity Day celebrates the reunification of Germany in 1990.",
    "31-05": "World No Tobacco Day aims to raise awareness about the health risks associated with tobacco use and advocate for effective policies to reduce tobacco consumption.",
    "4-04": "Children's Day is a day dedicated to the welfare and well-being of children, celebrated in many countries around the world.",
    "11-09": "Patriot Day in the United States commemorates the lives lost in the September 11, 2001 terrorist attacks.",
    "9-10": "World Post Day celebrates the establishment of the Universal Postal Union in 1874 and the importance of postal services worldwide.",
    "5-06": "World Environment Day raises awareness about environmental issues and encourages global action to protect the environment.",
    "8-05": "World Red Cross and Red Crescent Day honors the principles and efforts of the Red Cross and Red Crescent Societies worldwide.",
    "26-09": "European Day of Languages celebrates linguistic diversity in Europe and promotes language learning and cultural understanding.",
    "8-11": "International Day of Radiology raises awareness of the importance of imaging in the diagnosis and treatment of medical conditions.",
    "16-10": "World Food Day promotes awareness and action for those who suffer from hunger and for the need to ensure food security and nutritious diets for all.",
    "21-11": "World Television Day celebrates the impact of television on our lives and its role in shaping public opinion and entertainment.",
    "10-09": "World Suicide Prevention Day raises awareness about suicide prevention and promotes worldwide action to prevent suicides.",
    "1-04": "April Fools' Day is celebrated in many countries with pranks and jokes played on friends and family members.",
    "21-12": "Winter Solstice marks the shortest day and longest night of the year in the Northern Hemisphere, celebrated with festivals and traditions.",
    "9-08": "International Day of the World's Indigenous Peoples recognizes and promotes the rights of indigenous peoples worldwide.",
    "26-07": "International Day for the Conservation of the Mangrove Ecosystem promotes the importance of mangrove ecosystems for coastal biodiversity and sustainable development.",
    "22-03": "World Water Day raises awareness about the importance of freshwater and advocates for the sustainable management of water resources worldwide.",
    "29-09": "World Heart Day raises awareness about cardiovascular disease and promotes heart-healthy lifestyles worldwide.",

    # leftovers

     "10-05": "World Lupus Day raises awareness about lupus, a chronic autoimmune disease.",
    "21-03": "World Down Syndrome Day raises public awareness and promotes inclusion and understanding of people with Down syndrome.",
    "8-09": "International Literacy Day promotes literacy as a tool to empower individuals and societies.",
    "5-11": "Guy Fawkes Night, also known as Bonfire Night, commemorates the foiling of the Gunpowder Plot in 1605.",
    "24-07": "Pioneer Day is a state holiday in Utah, commemorating the arrival of the first Latter-day Saint pioneers in the Salt Lake Valley.",
    "17-07": "World Day for International Justice promotes international criminal justice and honors the role of the International Criminal Court.",
    "23-06": "United Nations Public Service Day celebrates the value and virtue of public service to the community.",
    "2-03": "Read Across America Day promotes reading and literacy among children and young people in the United States.",
    "1-06": "International Children's Day celebrates children and their well-being.",
    "23-05": "World Turtle Day raises awareness about turtle conservation and protection of their habitats.",
    "16-09": "International Day for the Preservation of the Ozone Layer raises awareness about the depletion of the ozone layer and efforts to protect it.",
    "4-06": "International Day of Innocent Children Victims of Aggression honors and protects the rights of children affected by violence.",
    "24-11": "International Day for the Elimination of Violence against Women raises awareness about gender-based violence and advocates for its prevention.",
    "26-03": "Purple Day is an international grassroots effort dedicated to increasing awareness about epilepsy worldwide.",
    "21-02": "International Mother Language Day promotes linguistic and cultural diversity and multilingualism.",
    "23-09": "International Day of Sign Languages raises awareness about the importance of sign languages as part of linguistic diversity and inclusion.",
    "18-05": "International Museum Day celebrates the role of museums as institutions that serve society and its development.",
    "20-03": "International Day of Happiness promotes happiness as a fundamental human goal and recognizes the importance of happiness in public policy objectives.",
    "29-07": "International Tiger Day raises awareness about tiger conservation and promotes global action to protect tigers.",
    "13-06": "International Albinism Awareness Day raises awareness about albinism and fights against discrimination faced by people with albinism.",
    "9-11": "World Freedom Day celebrates the fall of the Berlin Wall and the end of communism in Eastern Europe.",
    "14-09": "World First Aid Day promotes the importance of first aid training and measures to prevent injuries and save lives.",
    "7-05": "World Password Day raises awareness about the importance of password security and encourages people to strengthen their passwords.",
    "6-03": "World Wildlife Day raises awareness about the world's wild fauna and flora and the importance of conservation efforts.",
    "13-11": "World Kindness Day promotes kindness and goodwill among people.",
    "7-10": "World Habitat Day promotes the importance of safe and adequate housing for all.",
    "25-10": "World Pasta Day celebrates the delicious Italian dish and promotes its cultural significance worldwide.",
    "21-04": "World Creativity and Innovation Day celebrates creativity and innovation as essential for achieving the Sustainable Development Goals.",
    "12-02": "Darwin Day celebrates the anniversary of the birth of Charles Darwin and his contributions to science.",
    "14-03": "Pi Day celebrates the mathematical constant π (pi) and its significance in mathematics and science.",
    "10-11": "World Science Day for Peace and Development promotes the role of science in building a sustainable and peaceful world.",
    "7-09": "International Day of Clean Air for Blue Skies raises awareness about the importance of clean air for health and sustainable development.",
    "4-02": "World Cancer Day raises awareness about cancer prevention, detection, and treatment.",
    "2-12": "International Day for the Abolition of Slavery raises awareness about modern slavery and promotes efforts to eradicate it.",
    "14-07": "Bastille Day celebrates the French Revolution and the Storming of the Bastille on July 14, 1789.",
    "22-05": "International Day for Biological Diversity promotes biodiversity issues and encourages action to protect the Earth's ecosystems.",
    "18-10": "World Menopause Day raises awareness about menopause and supports women during this stage of life.",
    "19-07": "World Listening Day celebrates the practice of listening as it relates to the world around us, environmental awareness, and acoustic ecology.",
    "27-01": "International Holocaust Remembrance Day commemorates the Holocaust, the genocide that resulted in the deaths of six million Jews and millions of others.",
    "15-04": "World Art Day celebrates creativity, innovation, and the contributions of artists to cultural heritage and society.",
    "16-11": "International Day for Tolerance promotes tolerance, understanding, and respect among cultures and peoples.",
    "20-02": "World Day of Social Justice promotes efforts to tackle issues such as poverty, exclusion, and unemployment.",
    "21-08": "World Senior Citizens Day honors senior citizens and recognizes their contributions to society.",
    "14-10": "World Standards Day raises awareness about the importance of standardization and honors the contributions of experts who develop standards.",
    "5-02": "World Nutella Day celebrates the delicious hazelnut chocolate spread and its fans around the world.",
    "18-07": "Mandela Day celebrates the birthday of Nelson Mandela and encourages individuals to take action to change the world for the better.",
    "8-06": "World Oceans Day raises awareness about the importance of protecting the world's oceans and promotes ocean conservation efforts.",
    "26-11": "Thanksgiving Day celebrates the harvest and blessings of the past year with family and friends.",
    "10-10": "World Mental Health Day raises awareness about mental health issues and promotes efforts to support mental well-being worldwide.",
    "4-10": "World Animal Day celebrates animal life in all its forms and raises awareness about animal rights and welfare.",
    "5-10": "World Teachers' Day honors teachers and their contributions to education and development.",
    "24-09": "International Day of Sign Languages raises awareness about the importance of sign languages as part of linguistic diversity and inclusion.",
    "12-10": "World Arthritis Day raises awareness about arthritis and encourages early diagnosis, treatment, and management.",
    "12-05": "International Nurses Day honors nurses and their contributions to healthcare and society.",
    "15-06": "World Elder Abuse Awareness Day raises awareness about elder abuse and neglect and promotes dignity and respect for older adults.",
    "15-12": "International Tea Day celebrates the cultural heritage and health benefits of tea.",
    "3-11": "International Day of Persons with Disabilities promotes the rights and well-being of persons with disabilities in all spheres of society and development.",
    "4-12": "International Cheetah Day celebrates and raises awareness about cheetahs and their conservation.",
    "14-11": "World Diabetes Day raises awareness about diabetes, its prevention, and management.",
    "1-12": "World AIDS Day aims to raise awareness of the AIDS pandemic caused by the spread of HIV infection and to mourn those who have died of the disease.",
    "17-11": "World Prematurity Day raises awareness about preterm birth and the challenges faced by preterm babies and their families.",
    "2-12": "International Day for the Abolition of Slavery raises awareness about modern slavery and promotes efforts to eradicate it.",
      
}