country_to_timezone = {
  
    'usa': 'America/New_York',
    'india': 'Asia/Kolkata',
    'uk': 'Europe/London',
    'australia': 'Australia/Sydney',
    'canada': 'America/Toronto',
    'china': 'Asia/Shanghai',
    'france': 'Europe/Paris',
    'germany': 'Europe/Berlin',
    'italy': 'Europe/Rome',
    'japan': 'Asia/Tokyo',
    'mexico': 'America/Mexico_City',
    'russia': 'Europe/Moscow',
    'south africa': 'Africa/Johannesburg',
    'spain': 'Europe/Madrid',
    'brazil': 'America/Sao_Paulo',
    'argentina': 'America/Argentina/Buenos_Aires',
    'south korea': 'Asia/Seoul',
    'turkey': 'Europe/Istanbul',
    'saudi arabia': 'Asia/Riyadh',
    'united arab emirates': 'Asia/Dubai',
    'egypt': 'Africa/Cairo',
    'nigeria': 'Africa/Lagos',
    'kenya': 'Africa/Nairobi',
    'thailand': 'Asia/Bangkok',
    'singapore': 'Asia/Singapore',
    'indonesia': 'Asia/Jakarta',
    'malaysia': 'Asia/Kuala_Lumpur',
    'philippines': 'Asia/Manila',
    'vietnam': 'Asia/Ho_Chi_Minh',
    'pakistan': 'Asia/Karachi',
    'bangladesh': 'Asia/Dhaka',
    'sri lanka': 'Asia/Colombo',
    'new zealand': 'Pacific/Auckland',
    'greece': 'Europe/Athens',
    'netherlands': 'Europe/Amsterdam',
    'belgium': 'Europe/Brussels',
    'sweden': 'Europe/Stockholm',
    'norway': 'Europe/Oslo',
    'finland': 'Europe/Helsinki',
    'denmark': 'Europe/Copenhagen',
    'switzerland': 'Europe/Zurich',
    'austria': 'Europe/Vienna',
    'portugal': 'Europe/Lisbon',
    'ireland': 'Europe/Dublin',
    'poland': 'Europe/Warsaw',
    'czech republic': 'Europe/Prague',
    'hungary': 'Europe/Budapest',
    'israel': 'Asia/Jerusalem',
    'ukraine': 'Europe/Kiev',
    'romania': 'Europe/Bucharest',
    'bulgaria': 'Europe/Sofia',
    'croatia': 'Europe/Zagreb',
    'serbia': 'Europe/Belgrade',
    'slovakia': 'Europe/Bratislava',
    'slovenia': 'Europe/Ljubljana',
    'lithuania': 'Europe/Vilnius',
    'latvia': 'Europe/Riga',
    'estonia': 'Europe/Tallinn',
    'iceland': 'Atlantic/Reykjavik',
    'greenland': 'America/Godthab',
    'fiji': 'Pacific/Fiji',
    'samoa': 'Pacific/Apia',
    'tonga': 'Pacific/Tongatapu',
    'papua new guinea': 'Pacific/Port_Moresby',
    'hawaii': 'Pacific/Honolulu',
    'alaska': 'America/Anchorage',
    'chile': 'America/Santiago',
    'peru': 'America/Lima',
    'colombia': 'America/Bogota',
    'venezuela': 'America/Caracas',
    'uruguay': 'America/Montevideo',
    'paraguay': 'America/Asuncion',
    'bolivia': 'America/La_Paz',
    'ecuador': 'America/Guayaquil',
    'costa rica': 'America/Costa_Rica',
    'panama': 'America/Panama',
    'cuba': 'America/Havana',
    'dominican republic': 'America/Santo_Domingo',
    'haiti': 'America/Port-au-Prince',
    'jamaica': 'America/Jamaica',
    'trinidad and tobago': 'America/Port_of_Spain',
    'puerto rico': 'America/Puerto_Rico',
    'bahamas': 'America/Nassau',
    'barbados': 'America/Barbados',
    'bermuda': 'Atlantic/Bermuda',
    'belize': 'America/Belize',
    'guatemala': 'America/Guatemala',
    'honduras': 'America/Tegucigalpa',
    'nicaragua': 'America/Managua',
    'el salvador': 'America/El_Salvador',
    'luxembourg': 'Europe/Luxembourg',
    'monaco': 'Europe/Monaco',
    'san marino': 'Europe/San_Marino',
    'liechtenstein': 'Europe/Vaduz',
    'andorra': 'Europe/Andorra',
    'malta': 'Europe/Malta',
    'cyprus': 'Asia/Nicosia',
    'morocco': 'Africa/Casablanca',
    'tunisia': 'Africa/Tunis',
    'algeria': 'Africa/Algiers',
    'sudan': 'Africa/Khartoum',
    'ethiopia': 'Africa/Addis_Ababa',
    'tanzania': 'Africa/Dar_es_Salaam',
    'uganda': 'Africa/Kampala',
    'ghana': 'Africa/Accra',
    'ivory coast': 'Africa/Abidjan',
    'senegal': 'Africa/Dakar',
    'cameroon': 'Africa/Douala',
    'angola': 'Africa/Luanda',
    'zambia': 'Africa/Lusaka',
    'zimbabwe': 'Africa/Harare',
    'botswana': 'Africa/Gaborone',
    'mozambique': 'Africa/Maputo',
    'namibia': 'Africa/Windhoek',
    'madagascar': 'Indian/Antananarivo',
    'mauritius': 'Indian/Mauritius',
    'seychelles': 'Indian/Mahe',
    'maldives': 'Indian/Maldives',
    'nepal': 'Asia/Kathmandu',
    'bhutan': 'Asia/Thimphu',
    'myanmar': 'Asia/Yangon',
    'laos': 'Asia/Vientiane',
    'cambodia': 'Asia/Phnom_Penh',
    'brunei': 'Asia/Brunei',
    'east timor': 'Asia/Dili',
    'kazakhstan': 'Asia/Almaty',
    'uzbekistan': 'Asia/Tashkent',
    'turkmenistan': 'Asia/Ashgabat',
    'kyrgyzstan': 'Asia/Bishkek',
    'tajikistan': 'Asia/Dushanbe',
    'afghanistan': 'Asia/Kabul',
    'armenia': 'Asia/Yerevan',
    'azerbaijan': 'Asia/Baku',
    'georgia': 'Asia/Tbilisi',
    'mongolia': 'Asia/Ulaanbaatar',
    'north korea': 'Asia/Pyongyang'
}
